# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

npm-login: &npm-login
  # NPM_TOKEN is manually defined in CircleCI
  # project settings > Build settings > Environment variables
  # Add the NPM_TOKEN name and the value is your npm token
  # Get your npm token via npm token createOrUpdateUser
  # https://docs.npmjs.com/cli/token
  run:
    name: Create .npmrc
    command: |
      echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc

jobs:
  build:
    docker:
    # specify the version you desire here
    - image: circleci/node:10
    working_directory: ~/repo
    steps:
    # Check out the git repo to the working directory
    - checkout
    # Create the .npmrc file so npm can auth for publishing
    - *npm-login
    - add-ssh-keys:
        fingerprints:
        # You need to add a deploy key with write permission in order for the CI to commit changes
        # back to the repo
        # https://circleci.com/docs/2.0/gh-bb-integration/#adding-readwrite-deployment-keys-to-github-or-bitbucket
        - "4d:a0:5f:2e:f9:b7:6d:8d:80:85:17:94:90:7f:ab:f9"
    # Download and cache dependencies so subsequent builds run faster
    - restore_cache:
        keys:
        - dependencies-{{ checksum "package-lock.json" }}
        # fallback to using the latest cache if no exact match is found
        - dependencies-
    - run:
        name: Install deps
        command: |
          npm i
    - run:
        name: Install Hashicorp Vault
        command: |
          curl -sO https://releases.hashicorp.com/vault/1.1.2/vault_1.1.2_linux_amd64.zip
          unzip vault_1.1.2_linux_amd64.zip
          sudo mv vault /usr/local/bin/
          rm vault_1.1.2_linux_amd64.zip
    - run:
        name: Register test Certificiate Authority
        command: |
          sudo cp test-certs/rootCA.crt /etc/ssl/certs
    - save_cache:
        paths:
          - node_modules
        key: dependencies-{{ checksum "package-lock.json" }}
    - run:
        name: Run unit tests
        command: |
          npm run test
    - run:
        name: Run integration tests
        command: |
          npm run test:int
    - run:
        name: Build the libraries
        command: |
          npm run build
    - run:
        name: npm publish (master only)
        command: |
          .circleci/deploy.sh
